In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/1. project ecommerce archive (5).csv")
df.head()

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   object
 1   Product Name  3500 non-null   object
 2   Category      3500 non-null   object
 3   Region        3500 non-null   object
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Profit        3500 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 191.5+ KB

In [ ]:
df.isnull().sum()

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Category"].unique()

array(['Office', 'Accessories', 'Electronics'], dtype=object)

In [ ]:
df["Region"].unique()

array(['North', 'East', 'South', 'West'], dtype=object)

In [ ]:
df["Product Name"].unique()

array(['Printer', 'Mouse', 'Tablet', 'Camera', 'Headphones', 'Smartwatch',
       'Monitor', 'Smartphone', 'Keyboard', 'Laptop'], dtype=object)

In [ ]:
df[["Quantity", "Sales", "Profit"]].describe()

          Quantity         Sales       Profit
count  3500.000000   3500.000000  3500.000000
mean      4.931714   3047.966000   527.047203
std       2.575895   2440.213237   504.139732
min       1.000000     51.000000     6.970000
25%       3.000000   1049.500000   158.695000
50%       5.000000   2350.500000   361.070000
75%       7.000000   4537.000000   729.125000
max       9.000000  10782.000000  2946.930000

In [ ]:
df["Order Date"].dtype

dtype('O')

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [ ]:
df["Order Date"].dtype

dtype('<M8[ns]')

In [ ]:
df["Order Date"].min()

Timestamp('2022-01-01 00:00:00')

In [ ]:
df["Order Date"].max()

Timestamp('2024-12-31 00:00:00')

In [ ]:
df.dtypes

Order Date      datetime64[ns]
Product Name            object
Category                object
Region                  object
Quantity                 int64
Sales                    int64
Profit                 float64
dtype: object

In [ ]:
df[df["Quantity"]<=0]

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []

In [ ]:
df[df["Sales"]<=0]

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []

In [ ]:
df[df["Profit"]<=0]

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []